name: Deploy Next.js Frontend

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch of this repository

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest # Use a GitHub-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add Server to Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan 144.24.104.158 >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Deploy Frontend to Server via SSH
      run: |
        echo "Starting Next.js frontend deployment..."
        ssh ubuntu@144.24.104.158 "
          # --- BEGIN NVM SETUP FOR CI/CD ---
          # This ensures nvm is loaded for the non-interactive SSH session
          export NVM_DIR=\"\$HOME/.nvm\" && [ -s \"\$NVM_DIR/nvm.sh\" ] && \\. \"\$NVM_DIR/nvm.sh\"
          # Explicitly tell nvm to use Node.js version 20 for this session
          nvm use 20
          # --- END NVM SETUP FOR CI/CD ---

          # Now proceed with your deployment commands, which will use Node.js v20
          cd /var/www/projects/new-ui && \
          git pull origin main && \
          npm install --legacy-peer-deps && \
          npm run build && \
          pm2 restart nextjs-app
        "
        echo "Next.js frontend deployment complete."
